baseurl : /space
BASE_PATH : http://almatrix.github.io/space

highlighter: rouge
pygments: true
paginate: 10
gems:
  - jekyll-feed

archive_path: /space/posts.html
categories_path : /space/categories.html
tags_path : /space/posts.html

title : 美好地浪费生命
tagline: Javascript R
author : 
  name : Ming
  email : mingli.sgg@gmail.com
  github : https://github.com/almatrix
  weibo: own_miracle@sina.com

name: Enjoy Life | Ming's Blog
url: http://almatrix.github.io/space/
