baseurl : /space
BASE_PATH : http://almatrix.github.io/space

pygments: true
paginate: 5

title : 美好地浪费生命
tagline: Javascript R
author : 
  name : ming
  email : mingli.sgg@gmail.com
  github : https://github.com/almatrix