baseurl : /space
BASE_PATH : http://almatrix.github.io/space


pygments: true
paginate: 10


archive_path: /space/posts.html
categories_path : /space/categories.html
tags_path : /space/posts.html

title : 美好地浪费生命
tagline: Javascript R
author : 
  name : Ming
  email : mingli.sgg@gmail.com
  github : https://github.com/almatrix
  weibo: own_miracle@sina.com